version: "3.8"
services:
  web:
    build:
      context: ./
    volumes:
      - .:/opt/nodejs
      - /opt/nodejs/node_modules
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - griddb
  griddb:
    image: "griddbnet/griddb"
